# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/GitLocalRepo/Verilog-Design-Xilinx/Encoder/Encoder.cache/wt [current_project]
set_property parent.project_path C:/GitLocalRepo/Verilog-Design-Xilinx/Encoder/Encoder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/GitLocalRepo/Verilog-Design-Xilinx/Encoder/Encoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/GitLocalRepo/Verilog-Design-Xilinx/Encoder/Encoder.srcs/sources_1/new/decoder_for.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/GitLocalRepo/Verilog-Design-Xilinx/Encoder/Encoder.srcs/constrs_1/imports/Desktop/pri_encoder_fpga.xdc
set_property used_in_implementation false [get_files C:/GitLocalRepo/Verilog-Design-Xilinx/Encoder/Encoder.srcs/constrs_1/imports/Desktop/pri_encoder_fpga.xdc]


synth_design -top decoder_for -part xc7a100tcsg324-1


write_checkpoint -force -noxdef decoder_for.dcp

catch { report_utilization -file decoder_for_utilization_synth.rpt -pb decoder_for_utilization_synth.pb }
