# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Anahit Sarao/Documents/gitlocal/Verilog-Design/StorageBuildingBlocks/StorageBuildingBlocks.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Anahit Sarao/Documents/gitlocal/Verilog-Design/StorageBuildingBlocks/StorageBuildingBlocks.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Anahit Sarao/Documents/gitlocal/Verilog-Design/StorageBuildingBlocks/StorageBuildingBlocks.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Anahit Sarao/Documents/gitlocal/Verilog-Design/StorageBuildingBlocks/StorageBuildingBlocks.srcs/sources_1/new/storage_top.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Anahit Sarao/Documents/gitlocal/Verilog-Design/StorageBuildingBlocks/StorageBuildingBlocks.srcs/constrs_1/new/fifo.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Anahit Sarao/Documents/gitlocal/Verilog-Design/StorageBuildingBlocks/StorageBuildingBlocks.srcs/constrs_1/new/fifo.xdc}}]


synth_design -top storage_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef storage_top.dcp

catch { report_utilization -file storage_top_utilization_synth.rpt -pb storage_top_utilization_synth.pb }
