# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/subtractor.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/div_y_reg.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/div_x_reg.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/div_ud_cntr.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/div_r_reg.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/comparator.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/mux2.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/smallCalc_rf.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/smallCalc_alu.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/mux1.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/div_datapath.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/div_cntrl_unit.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/smallCalc_datapath.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/smallCalc_ctrl_unit.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/divider.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/smallCalc.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/multi_cla.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/multiplier.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/multi_shifter.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/d_reg.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/multi_pp.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/cla_gen.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/half_adder.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/and_mod.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/full_datapath.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/full_control_unit.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/fullcalc.v}
  {C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/sources_1/new/fullcalcFPGA.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/constrs_1/new/calcsys_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Anahit Sarao/Documents/calcsys_integration/calcsys_integration.srcs/constrs_1/new/calcsys_constraints.xdc}}]


synth_design -top calcsys_top_level -part xc7a100tcsg324-1


write_checkpoint -force -noxdef calcsys_top_level.dcp

catch { report_utilization -file calcsys_top_level_utilization_synth.rpt -pb calcsys_top_level_utilization_synth.pb }
